baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'nightfall'

[menu]
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"

[params]
user = "bani"
hostname = "gohugo.io"


[params.author]
name = "Bani"
email = "arobbanii5@gmail.com"
avatarFirst = false

[[params.social]]
key = 0
name = "github"
url = "https://github.com/babanini95"
# icon = "fa-brands fa-github"  # Add link to your icon font to `layouts/partials/custom-head.html`
target = "_blank" # Defines your target option in a-href. _blank for a new Tab for example.
aria = "GitHub Profile" # Define the aria label for accessibility like page reader - this is better for your SEO

[[params.social]]
key = 1
name = "linkedin"
url = "https://www.linkedin.com/in/arobbani/"

[[params.social]]
key = 2
name = "twitter"
url = "https://x.com/arobbaniii"

[[params.social]]
key = 3
name = "email"
url = "mailto:arobbanii5@gmail.com"
